### ISSUE TITLE
Missing settings

### ISSUE THREAD

**Issue by TTSKarlsson** [YOYZHANG/vs-emoji-intellisense#1]
![20230509_172842_654x108](https://github.com/YOYZHANG/vs-emoji-intellisense/assets/9962943/115cca4a-ac9c-454b-8264-d17dac926e1b)

example:
![20230509_173047_408x247](https://github.com/YOYZHANG/vs-emoji-intellisense/assets/9962943/19e92664-5308-4222-b04f-35fd95332934)

expected:
Setting not to be greyed out when the extension is active and to enable emoji intellisense in listed languages.

instead:
Setting is greyed out and emoji intellisense is not enabled in the listed languages.

info:
The extension is proven to be active because it works in markdown files.

**Comment by YOYZHANG** [comment]
Thank you for bringing this issue!  The bug has been fixed in the latest version: Release 0.2.2. 
I recommend updating to the latest version and trying again. Please let me know if you encounter any further issues, and I will be happy to assist you.😄

**Comment by YOYZHANG** [comment]
Thank you for bringing this issue! The bug has been fixed in the latest version: Release 0.2.2.
I recommend updating to the latest version and trying again. Please let me know if you encounter any further issues, and I will be happy to assist you.😄
